### ISSUE TITLE
CI, docs and build script

### ISSUE THREAD

**Issue by matthid** [alexreg/ircdotnet#3]
Good to see that the project is still kind of alive :+1: .
If you want to move the project forward I would suggest to add a build system (I recommend [FAKE](https://github.com/fsharp/FAKE)) and and CI ([travis](https://travis-ci.org/) and [appveyor](https://ci.appveyor.com/)). FAKE can automatically build the nuget packages and we could try to support multiple builds people have developed here on github (I saw WinRT and WindowsPhone specific commits).

Because there is a lot of documentation in the code I would also recommend using [FSharp.Formatting](https://github.com/tpetricek/FSharp.Formatting/) to generate a documentation page.

PS: I used all this with success on [RazorEngine](https://github.com/Antaris/RazorEngine) which now has a nice [documentation page](http://antaris.github.io/RazorEngine/) automatically generated from the markup files and the code documentation in the repository.

The basic structure is already there and FAKE is very flexible so there are not too many changes needed... I think most things can just be copied from the RazorEngine repository.

In the future unit tests can be added they will be run on windows and linux on any new pull requests!

What do you think?
I would work on this myself but I have some other things to do, but if someone wants to start this and needs and hints feel free to ask!

**Comment by alexreg** [comment]
All useful suggestions, I agree. Alas, I don't have the time to do this updating work either right now. I've integrated outstanding fixes and made a few myself tonight (as well as cleaned up some miscellaneous things), but I can't see myself getting more opportunity to work on this any time soon!

That said, if someone wishes to take this on, and wants advice from me, feel free to ask questions here and I'll try to respond promptly! Alternatively, ping me on IRC (Freenode, nick 'Noldorin') and we can talk.

**Comment by matthid** [comment]
Ok nice to know, so you would accept (a possibly larger -> moving files around) pull request in this area? I can maybe work on this as a side project in the next couple of days.

**Comment by alexreg** [comment]
Certainly! I would urge you or anyone else making such big changes to document them well in commit messages, and generally make lots of small commits for each change, where possible… but otherwise, I am happy to accept such a ‘modernisation’ of the project. I would be grateful if you had a go at this in fact. Feel free to check anything with me.
