### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by PureDecimation** [alexreg/IrcDotNet#7]
Getting this error when I try to run the build script. Not sure what is causing it. Seems to be git related as that is what is thrown everywhere in the code. I have the latest version of git, so not sure what is going on.

Resolve build dependencies
All packages listed in packages.config are already installed.
Starting build
git.exe rev-parse HEAD

F# Interactive for F# 3.1 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\Users\Tyler\Desktop\IrcDotNet-develop\buildConfig.fsx
 Loading C:\Users\Tyler\Desktop\IrcDotNet-develop\build.fsx]

System.TypeInitializationException: The type initializer for '<StartupCode$FSI_0001>.$FSI_0001_BuildConfig$fsx' threw an
 exception. ---> System.Exception: Could not run "git rev-parse HEAD".
Error: Start of process git.exe failed. The system cannot find the file specified
   at Fake.Git.CommandHelper.runSimpleGitCommand@89-2.Invoke(String message) in D:\code\fake\src\app\FakeLib\Git\Command
Helper.fs:line 89
   at Fake.Git.CommandHelper.runSimpleGitCommand(String repositoryDir, String command) in D:\code\fake\src\app\FakeLib\G
it\CommandHelper.fs:line 89
   at Fake.Git.Branches.getSHA1(String repositoryDir, String commit) in D:\code\fake\src\app\FakeLib\Git\Branches.fs:lin
e 32
   at <StartupCode$FSI_0001>.$FSI_0001_BuildConfig$fsx..cctor() in C:\Users\Tyler\Desktop\IrcDotNet-develop\buildConfig.
fsx:line 38
   --- End of inner exception stack trace ---
   at <StartupCode$FSI_0001>.$FSI_0001_Build$fsx.main@() in C:\Users\Tyler\Desktop\IrcDotNet-develop\build.fsx:line 38
Stopped due to error

**Comment by matthid** [comment]
You can either install http://git-scm.com/ in it's default location (%program files%/Git/bin should contain a git.exe) or make the environment variable GIT point to a working git.exe.

**Comment by PureDecimation** [comment]
My git is installed there. It's in program files (x86) more specifically, but that shouldn't make a difference should it?

**Comment by matthid** [comment]
this looks really weird... anything unusual about your setup? How do you start the build? VS and Windows version? Is your GIT environment variable set?

**Comment by PureDecimation** [comment]
I'll be honest, I'm not entirely sure. I'm new to this. I've always just used default libraries in the past. So building and installing external ones are a bit foreign to me.

**Comment by matthid** [comment]
Yeah no problem, no need to understand the build process. It should in theory work and do everything for you out of the box!

I'm just trying to figure out why it fails for you, so I need you to answer my previous questions. Especially I need to now how you start the process (step by step). Normally you open a command prompt, navigate to the folder and write "build".

**Comment by PureDecimation** [comment]
Yes, I am executing by typing build into cmd in the file path. Nothing unusual about my setup, even tried it on a second compute rwith the exact same result. Using vs2013 and windows 7 on 1 computer, 8.1 on the one I initially tried it on. As for GIT environment variable, I'm not sure. I Googled and looked into it but I couldn't figure out exactly what you meant by that.

**Comment by matthid** [comment]
Ok try the following things (always logoff-logof, or restart!):
* Add git to your path: Right click on "This PC" -> Properties -> Advanced System Settings -> Environment Variables -> System variables -> Select "Path" -> Edit... -> Append `;C:\Program Files (x86)\Git\bin`. There is also an option in the git installer to do that automatically.
* If that doesn't work try adding a `GIT` environment variable in the same menu (either as user variable or system variable, both should work). The variable should be the full path to `git.exe`

Please report back the results.

But I'm still not sure why you need to do that in the first place. FAKE should normally be able to figure the path out. Do you have a `git bash` in the startmenu? What does `git --version` say in the git bash?

**Comment by PureDecimation** [comment]
git --version returns "git version 1.9.5.msysgit.0"

Still not working with these new steps. :/

**Comment by matthid** [comment]
Wow I have no idea what else to check actually...

/cc @forki as it seems to be related to FAKE, any idea what might go on here?
The code that seems to fail is: `let commitHash = Information.getCurrentSHA1(".")`

**Comment by alexreg** [comment]
I agree with @matthid here… the issue seems odd, unless your environment is somehow messed up. These sound like good steps to try though, so report back.

**Comment by alexreg** [comment]
msysgit? Is that the default Git installation on Windows? Anyway, 1.9.5 is quite outdated; try installing a new version.

**Comment by PureDecimation** [comment]
1.9.5 is the latest maintained version. It is the one that is downloaded when you go to the site. About 2 months old. Wasn't sure if I should be using the (what I assume are) beta version. I can try it if you think that would help. Although that would be an odd fix.

**Comment by alexreg** [comment]
Really? I’m on 2.3.0. My goodness…

**Comment by PureDecimation** [comment]
Is the build function on your machines? If so, then its almost certainly something on my end. Are there any other dependencies this relies on besides just git? Or specific git dependencies? I found last night that when I ran the build.sh file in a git shell it requested mono dependencies. I mono installed with all recommended features though. Not sure if it might be related.

**Comment by matthid** [comment]
I use this build system on various different projects and it always worked.
You can use the task-manager to figure out if a mono process is started (it shouldn't when cmd -> "build.cmd" is used)
No mono is required to build and the only dependencies I can think of are git and F#. All other dependencies are downloaded automatically.

**Comment by PureDecimation** [comment]
Well, I'll look more into it when I get home. I have a friend that is going to try to it out as well. I'll let you know if we get any results.

**Comment by PureDecimation** [comment]
My mono install actually didn't work correctly because I didn't have the x86 c++ redistributes. Got them and installed mono and it worked the second time. I didn't catch what error it through the first time cause my command prompt closed on me. But I officially have it built. Definitely was a problem with the lack of mono.

**Comment by matthid** [comment]
Just to clarify: Mono is NOT required on windows. The only case it is required is when executing `build.sh` instead of `build.cmd` (or using `build` in a git bash instead of a windows command line (cmd)). And that's more of a limitation of `build.sh` than a requirement. `build.sh` is written for linux/mac systems.
