### ISSUE TITLE
NuGet out of date

### ISSUE THREAD

**Issue by fritogotlayed** [alexreg/IrcDotNet#9]
I did a search in NuGet and saw this project. It looks like NuGet is still on version 0.4.1 while the code here is at 0.5.0. Are their plans to keep these in sync?

**Comment by alexreg** [comment]
Hello. I’m afraid not… I’m not sure how to get the build system to automatically publish to NuGet. If this can be done however, I’d be happy to include it. Feel free to submit a pull request.

**Comment by fritogotlayed** [comment]
Hey @alexreg. I think this is more a configuration issue on the build server than it is a "pull request-able" issue. Maybe I'm wrong here as having automatically built NuGet packages is something that was already configured on my project at work so I don't know the intimate details. My understanding is the `csproj` had a line added to it that triggered NuGet to build the package. From there our TeamCity instance handled moving the package to a location that OctopusDeploy could then use to update our various servers. I'm not really sure if that helps but I like giving too much info rather than not enough.

**Comment by alexreg** [comment]
I believe this can still be done via a pull request.

Anyway, any thoughts on how to do this, @matthid?

**Comment by matthid** [comment]
I don't think there is a real need for automatic push to nuget via build server for this project.
Just building the project and manually uploading the package to nuget should be fine for now (as there aren't a lot of releases currently). This should be working already so I don't think we need any change here.

**Comment by alexreg** [comment]
What exactly should be uploaded to NuGet now?

**Comment by matthid** [comment]
The general release procedure is the following: 

1. Edit "buildConfig.fsx" and update the target version (0.5 in this case)
2. Edit "doc/ReleaseNotes.md" and enter some release notes.
3. Run "build Release" via cmd
4. Upload "release/nuget/IrcDotNet.0.*.nupkg" (should be the same version as edited above) to NuGet.

**Comment by alexreg** [comment]
Thank you, @matthid. This is all done from the 'master' branch right? If so, I can do it right now.

**Comment by alexreg** [comment]
Okay, all done. The new NuGet package is available at https://www.nuget.org/packages/IrcDotNet/0.5.0 <https://www.nuget.org/packages/IrcDotNet/0.5.0>.

**Comment by fritogotlayed** [comment]
@alexreg @matthid Thanks! :+1:

**Comment by alexreg** [comment]
Sure. Hope that does the job!
